### ISSUE TITLE
Issue with exemplar field

### ISSUE THREAD

**Issue by malcolm061990** [weastur/grafana-dashboards#1]
Hi. 
Big thanks for your cool clickhouse dashboard for grafana! :)
But I have some issue with it.
You have "exemplar" field in your graphs that is enabled by default. And for some reason when it's enabled I got 404 issue. If I disable exemplar I get the values correctly.
I have grafana 7.4.3 in kubernetes and some clickhouse instances outside of kubernetes.

PS: кстати, Паша, привет) может меня узнал?)))

**Comment by psapezhka** [comment]
Thanks. It seems that exemplars are useless for ClickHouse now, so I disabled it by default. 

P.S. Да )
